name: CI

# Cancel prev CI if new commit come
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - v*.*
  pull_request:
    branches:
      - main
      - v*.*
    paths:
      - 'client/**'
      - 'packages/**'
      - 'server/**'
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml

jobs:
  unittest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        node-version: [24.x]
        ci-project: [node, jsdom]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install libsecret-1
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt-get update && sudo apt-get install -y libsecret-1-dev

      - name: Install
        env:
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
        run: |
          pnpm install --frozen-lockfile
          pnpm run check:versions

      - name: CI
        run: |
          pnpm run ci --selectProjects ${{ matrix.ci-project }}

      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CORE_CODECOV_TOKEN }}
          flags: ${{ matrix.ci-project }}
          directory: ./coverage
