name: Deploy Iconfont Page

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/core-browser/src/style/icon/**'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: opensumi/actions/bot-token@main
        id: bot-token
        with:
          token-server: ${{ secrets.BOT_TOKEN_SERVER }}
          flag: ${{ secrets.BOT_FLAG }}
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: pnpm
      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm run update:iconfont

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          publish_dir: ./packages/components/src/icon/iconfont
